<?php

namespace Database\Seeders;

use App\Models\Paragraph;
use Illuminate\Database\Seeder;

class ParagraphSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $paragraphs = [
            // --- ENGLISH ---
            
            // EASY (Short, ~15-20 words)
            ['difficulty' => 'easy', 'language' => 'en', 'content' => 'The quick brown fox jumps over the lazy dog. This simple exercise helps you warm up your fingers quickly.'],
            ['difficulty' => 'easy', 'language' => 'en', 'content' => 'Learning to type fast is a valuable skill. It saves you time every day when communicating with your friends.'],
            
            // MEDIUM (Moderate, ~40-50 words)
            ['difficulty' => 'medium', 'language' => 'en', 'content' => 'Sustainability is no longer just a buzzword; it is a critical necessity for the future of our planet. As individuals, we can make a difference by reducing our carbon footprint, recycling materials, and choosing renewable energy sources to protect the environment for future generations.'],
            ['difficulty' => 'medium', 'language' => 'en', 'content' => 'The evolution of the internet has completely changed how we access information and connect with people across the globe. What used to take days of research in a physical library can now be accomplished in just a few seconds with a simple search engine query.'],
            ['difficulty' => 'medium', 'language' => 'en', 'content' => 'Effective communication is the cornerstone of any successful relationship, whether it is personal or professional. Listening actively and expressing your thoughts clearly can prevent many misunderstandings and help build a stronger bond between individuals who work together to achieve common goals.'],
            ['difficulty' => 'medium', 'language' => 'en', 'content' => 'The digital revolution has reshaped the way we perceive intellectual property and creative works worldwide. With the rise of streaming platforms, artists must find new ways to monetize their content while protecting their rights in an increasingly interconnected and globally accessible digital marketplace.'],
            
            // HARD (Long & Technical, ~80+ words)
            ['difficulty' => 'hard', 'language' => 'en', 'content' => 'The intricate architecture of distributed systems requires a profound understanding of consensus algorithms, data replication strategies, and network latency mitigation techniques for scaling. When designing highly available microservices, engineers must account for the CAP theorem, which states that it is impossible for a distributed data store to simultaneously provide more than two out of three guarantees: Consistency, Availability, and Partition Tolerance. This requires careful trade-offs based on specific requirement of the application.'],
            ['difficulty' => 'hard', 'language' => 'en', 'content' => 'Quantum entanglement is a physical phenomenon that occurs when a pair or group of particles is generated, defined, or interacts in such a way that the quantum state of each particle cannot be described independently of the state of the others, even when the particles are separated by a large distance. This counterintuitive behavior is a fundamental aspect of quantum mechanics that challenges our classical understanding of space and time, leading to breakthroughs in secure communication.'],
            ['difficulty' => 'hard', 'language' => 'en', 'content' => 'Heuristic evaluation is a usability inspection method for computer software that helps to identify usability problems in the user interface design. It specifically involves examiners judging the compliance of the interface with recognized usability principles, also known as heuristics. By applying these standardized rules, developers can ensure that their applications are intuitive, efficient, and accessible to a wide range of users, ultimately improving the overall quality and success of the digital product.'],
            ['difficulty' => 'hard', 'language' => 'en', 'content' => 'The phenomenon of deep learning, a subset of machine learning, relies on artificial neural networks with multiple layers to model complex patterns in data. These architectures have revolutionized speech recognition, computer vision, and natural language processing by enabling machines to learn hierarchical representations. As computational power increases and datasets grow larger, these models continue to push the boundaries of what is possible in artificial intelligence, impacting everything from healthcare to transportation.'],
            ['difficulty' => 'hard', 'language' => 'en', 'content' => 'A cryptographic hash function is a mathematical algorithm that maps data of arbitrary size to a bit array of a fixed size. It is a one-way function, meaning it is practically infeasible to invert or reverse the calculation to find the original input data. These functions are essential components of modern digital security, providing integrity checks for transmitted data and serving as the foundation for digital signatures, password storage, and various blockchain technologies used today.'],
            ['difficulty' => 'hard', 'language' => 'en', 'content' => 'Advanced machine learning models like Transformers utilize self-attention mechanisms to weigh the significance of different parts of the input data dynamically. This architecture has been pivotal in the development of large language models that can generate human-like text and perform complex reasoning across various domains. By processing entire sequences of data in parallel, Transformers offer significant performance improvements over traditional recurrent neural networks, leading to a new era of generative artificial intelligence.'],
            ['difficulty' => 'hard', 'language' => 'en', 'content' => 'The Byzantine Generals Problem is a classic thought experiment in computer science that illustrates the difficulty of reaching consensus in a distributed system where some components may fail or act maliciously. Solving this problem is fundamental to the security and reliability of modern blockchain technologies and decentralized networks. It requires robust protocols that can tolerate arbitrary faults while still ensuring that all honest participants agree on a single version of the truth across the network.'],

            // --- INDONESIAN ---
            
            // EASY (Short, ~15-20 words)
            ['difficulty' => 'easy', 'language' => 'id', 'content' => 'Saya sedang belajar mengetik dengan sepuluh jari agar pekerjaan saya menjadi lebih cepat selesai. Latihan rutin adalah kunci utama untuk mencapai kecepatan maksimal.'],
            ['difficulty' => 'easy', 'language' => 'id', 'content' => 'Mengetik cepat sangat berguna untuk mengerjakan tugas sekolah atau pekerjaan kantor. Jari-jari Anda akan bergerak secara otomatis tanpa perlu lagi melihat keyboard.'],
            
            // MEDIUM (Moderate, ~40-50 words)
            ['difficulty' => 'medium', 'language' => 'id', 'content' => 'Indonesia memiliki kekayaan budaya yang sangat luar biasa dari Sabang sampai Merauke. Keragaman bahasa, adat istiadat, dan kuliner menjadikan negara ini salah satu tempat yang paling unik dan menarik untuk dikunjungi oleh wisatawan dunia yang mencari pengalaman autentik dan berkesan.'],
            ['difficulty' => 'medium', 'language' => 'id', 'content' => 'Teknologi informasi telah berkembang sangat pesat dalam satu dekade terakhir. Sekarang kita bisa berkomunikasi dengan siapa saja di seluruh dunia hanya dengan menggunakan ponsel pintar yang terhubung ke jaringan internet yang stabil, memungkinkan pertukaran informasi secara instan setiap saat.'],
            ['difficulty' => 'medium', 'language' => 'id', 'content' => 'Penting bagi kita untuk menjaga kesehatan mata saat bekerja di depan layar komputer dalam waktu yang lama. Cobalah untuk menerapkan aturan dua puluh menit, yaitu setiap dua puluh menit melihat sesuatu yang jauh selama dua puluh detik agar otot mata tetap rileks dan sehat.'],
            ['difficulty' => 'medium', 'language' => 'id', 'content' => 'Pendidikan karakter sejak usia dini sangat penting untuk membangun fondasi moral yang kuat bagi generasi penerus bangsa. Nilai-nilai seperti kejujuran, kerja keras, dan empati harus diajarkan melalui keteladanan agar anak-anak dapat tumbuh menjadi pribadi yang berintegritas tinggi di masa depan.'],
            
            // HARD (Long & Technical, ~80+ words)
            ['difficulty' => 'hard', 'language' => 'id', 'content' => 'Transformasi digital di era industri modern menuntut setiap individu untuk memiliki literasi teknologi yang mumpuni. Integrasi antara kecerdasan buatan, mesin pembelajar, dan sistem otomasi telah mengubah lanskap pekerjaan secara global saat ini. Hal ini memerlukan adaptasi yang sangat cepat serta komitmen untuk melakukan pembelajaran berkelanjutan demi menjaga relevansi di pasar kerja yang semakin kompetitif dan penuh tantangan teknologi canggih yang terus berkembang pesat tanpa henti setiap harinya.'],
            ['difficulty' => 'hard', 'language' => 'id', 'content' => 'Implementasi kebijakan fiskal yang berkelanjutan memerlukan analisis mendalam terhadap berbagai variabel ekonomi makro yang saling berkaitan. Pemerintah harus mampu menyeimbangkan antara pengeluaran publik untuk pembangunan infrastruktur nasional dan upaya menjaga stabilitas nilai tukar mata uang dalam menghadapi gejolak ekonomi global. Melalui pengelolaan anggaran yang transparan dan akuntabel, sebuah negara dapat mencapai pertumbuhan ekonomi yang inklusif dan memberikan kesejahteraan bagi seluruh lapisan masyarakat secara merata.'],
            ['difficulty' => 'hard', 'language' => 'id', 'content' => 'Kriptografi merupakan disiplin ilmu yang mempelajari teknik-teknik komunikasi aman dari gangguan pihak ketiga yang tidak bertanggung jawab. Di era digital yang penuh dengan ancaman siber, penggunaan algoritma enkripsi yang kuat sangat krusial untuk melindungi integritas dan kerahasiaan data pribadi pengguna internet di seluruh dunia. Tanpa adanya sistem keamanan yang handal, informasi sensitif seperti transaksi keuangan atau identitas personal dapat dengan mudah disalahgunakan oleh pihak yang ingin melakukan kejahatan digital.'],
            ['difficulty' => 'hard', 'language' => 'id', 'content' => 'Konsep keberlanjutan lingkungan mengacu pada kemampuan untuk memenuhi kebutuhan manusia saat ini tanpa harus mengorbankan kemampuan generasi mendatang untuk memenuhi kebutuhan mereka sendiri. Hal ini melibatkan pengelolaan sumber daya alam yang bijaksana, pengurangan emisi gas rumah kaca, dan pelestarian keanekaragaman hayati yang semakin terancam oleh aktivitas manusia yang tidak terkontrol. Kesadaran kolektif dari seluruh lapisan masyarakat internasional sangat diperlukan untuk mencegah dampak buruk dari perubahan iklim yang ekstrem.'],
            ['difficulty' => 'hard', 'language' => 'id', 'content' => 'Paradigma pemrograman fungsional menekankan penggunaan fungsi murni tanpa mengubah status data atau menghasilkan efek samping yang tidak diinginkan dalam pengembangan perangkat lunak. Pendekatan ini memudahkan pengembang dalam melakukan pengujian kode dan memastikan keandalan sistem perangkat lunak yang kompleks melalui abstraksi matematika yang elegan. Dengan meminimalkan perubahan status yang tidak terduga, pemrograman fungsional membantu menciptakan aplikasi yang lebih mudah dipelihara, skalabel, dan bebas dari kutu atau kesalahan logika yang rumit.'],
            ['difficulty' => 'hard', 'language' => 'id', 'content' => 'Analisis data besar atau Big Data dalam sektor kesehatan memungkinkan deteksi dini penyebaran wabah penyakit secara lebih akurat dan tepat waktu. Dengan memanfaatkan algoritma pemrosesan data real-time, tenaga medis dan pemerintah dapat mengambil tindakan preventif yang lebih efektif untuk melindungi masyarakat dari potensi ancaman kesehatan yang terus mengintai. Integrasi data rekam medis elektronik dan informasi demografis membantu menciptakan kebijakan kesehatan publik yang lebih terarah dan berbasis pada bukti nyata di lapangan.'],
            ['difficulty' => 'hard', 'language' => 'id', 'content' => 'Keamanan siber di sektor perbankan merupakan prioritas utama mengingat meningkatnya ancaman serangan digital terhadap infrastruktur keuangan nasional yang sangat vital. Penggunaan otentikasi multi-faktor dan sistem deteksi intrusi berbasis kecerdasan buatan menjadi sangat krusial dalam memitigasi risiko pencurian data dan dana nasabah. Perusahaan keuangan juga harus rutin melakukan audit keamanan dan simulasi serangan untuk memastikan bahwa seluruh lapisan pertahanan mereka tetap kokoh menghadapi taktik peretasan yang semakin canggih.'],
        ];

        foreach ($paragraphs as $p) {
            Paragraph::create($p);
        }
    }
}
